# Generated by Django 4.1 on 2022-08-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
            ],
        ),
    ]
